# Default values for dveapiChart.

prjName: dveapi
domain: dve.example.local
apiVersion: 0.1.0
staticVersion: 0.1.0

storage:
  local: false
  localClaim: false
  class: dve-localstorage
  claim: dve-pvc
  path: /var/www/data

replicaCount: 1



