---
version: "3.9"
services:
  #djdb:
  #  image: postgres
  #    #restart: always
  #  environment:
  #    POSTGRES_USER: "djangoDb"
  #    POSTGRES_PASSWORD: "dbpwer1234"
  #    PGDATA: "/var/lib/postgresql/data/pgdata"
  #  volumes:
  #    - ./postgres:/var/lib/postgresql/data

  #      #networks:
  #      #  - djNet

  #my-adminer:
  #  image: adminer
  #  ports:
  #    - 8801:8080

  avgwebapi:
    image: dveapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGO_DATA_PATH: "/var/www/data/"
      DJANGO_STATIC_HOSTNAME: "dveapi-static"
    ports:
      - 8881:80
    volumes:
      - /var/www/data/:/var/www/data

  dveapi-static:
    image: dve-static
    build:
      context: .
      dockerfile: static.Dockerfile
      args:
        API_VERSION: latest
        API_NAME: dveapi
    ports:
      - 8882:80
    volumes:
      - /var/www/data/archive:/var/www/data/archive

