---
version: "3.9"
services:

  #my-adminer:
  #  image: adminer
  #  ports:
  #    - 8801:8080

  dveapi:
    image: dveapi:0.1.0
    build:
      context: .
      dockerfile: dveapi.Dockerfile
    environment:
      DJANGO_DATA_PATH: "/var/www/data/"
      DJANGO_STATIC_HOSTNAME: "dveapi-static"
      DJANGO_STORAGE_PATH: "/var/www/data/"
      DJANGO_DB_NAME: "djangoDb"
      DJANGO_DB_USER: "djangoDb"
      DJANGO_DB_PASSWORD: "dbpwer1234"
      DJANGO_DB_HOST: "dve-db"
    ports:
      - 8801:80
    volumes:
      - ./data:/var/www/data

  dve-db:
    image: postgres
      #restart: always
    environment:
      POSTGRES_USER: "djangoDb"
      POSTGRES_PASSWORD: "dbpwer1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  #      #networks:
  #      #  - djNet

  dveapi-static:
    image: dveapi-static:0.1.0
    build:
      context: .
      dockerfile: static.Dockerfile
      args:
        API_VERSION: 0.1.0
        API_NAME: dveapi
    ports:
      - 8802:80
    volumes:
      - ./data:/var/www/data/storage

