apiVersion: v1
kind: Service
metadata:
  name: {{.Values.prjName}}
  labels:
    app: {{.Values.prjName}}
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: {{.Values.prjName}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.prjName}}-static
  labels:
    app: {{.Values.prjName}}-static
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: {{.Values.prjName}}-static


