---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prjName }}
  labels:
    app: {{ .Values.prjName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prjName }}
  template:
    metadata:
      labels:
        app: {{ .Values.prjName }}
    spec:
      containers:
        - name: {{ .Values.prjName }}
          image: localhost:32000/dveapi:{{.Values.apiVersion}}
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/data
              name: pvc
          env:
            - name: DJANGO_STATIC_URL
              value: "http://static.{{.Values.domain}}:80/static/"
            - name: DJANGO_DATA_PATH
              value: "/var/www/data"
            - name: DJANGO_STORAGE_PATH
              value: "/var/www/data"

      volumes:
        - name: pvc
          persistentVolumeClaim:
              {{ if .Values.storage.localClaim }}
              claimName: {{.Values.prjName}}-pvc
              {{ else }}
              claimName: {{.Values.storage.claim}}
              {{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.prjName}}-static
  labels:
    app: {{.Values.prjName}}-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.prjName}}-static
  template:
    metadata:
      labels:
        app: {{.Values.prjName}}-static
    spec:
      containers:
        - name: {{.Values.prjName}}-static
          image: localhost:32000/dveapi-static:{{.Values.staticVersion}}
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/data/storage
              name: pvc
              readOnly: true
      volumes:
        - name: pvc
          persistentVolumeClaim:
              {{ if .Values.storage.localClaim }}
              claimName: {{.Values.prjName}}-pvc
              {{ else }}
              claimName: {{.Values.storage.claim}}
              {{ end }}

