apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.prjName}}
spec:
  rules:
  - host: api.{{.Values.domain}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.prjName}}
            port:
              number: 80
  - host: static.{{.Values.domain}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.prjName}}-static
            port:
              number: 80

