{{ if .Values.storage.local }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{.Values.prjName}}-localstorage
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /var/www/data
volumeBindingMode: WaitForFirstConsumer
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.prjName}}-pvc
spec:
  {{ if .Values.storage.local }}
  storageClassName: {{.Values.prjName}}-localstorage
  {{ else }}
  storageClassName: {{.Values.prjName}}-localstorage
  {{ end }}
  accessModes: [ReadOnlyMany]
  resources: { requests: { storage: 1Gi } }

